### ISSUE TITLE
Mega caselist dataset

### ISSUE THREAD

**Issue by vizowl** [Science-Media-Centre-NZ/tidy-covid-nz#2]
It would be useful to have a dataset that combined all the caselist files from the tidy directory. 

I think it is just bind_rows on all the days datasets in the tidy directory - but it would be useful to build that into the tidying script.

**Comment by nzwormgirl** [comment]
I've added `allCaseLists.RData` to the `data/moh/caselists/tidy` directory which has  two dataframes. One with all the caselists (`allTidyData`) and one with all the name changes (`allNameChanges`). Each has a `datasource` and `releasedate` column, so you should easily be able to pull out a specific day's caselist info. 

Also pairs with four functions for getting the latest caselists/namechanges or those for a specific date

- `getLatestCaseList`
- `getCaseList`
- `getLatestNameChanges`
- `getNameChanges`
